name: lumo

include:
    - path: services/valkey.yaml
    - path: services/seq.yaml
    - path: services/jaeger.yaml
    - path: services/gateway.yaml
    - path: services/auth.yaml
    - path: services/main.yaml
    - path: services/notifications.yaml
    - path: services/rabbitmq.yaml
    - path: databases/auth-database.yaml
    - path: databases/main-database.yaml
    - path: databases/notifications-database.yaml

networks:
    lumo-network:
        name: lumo-network
        driver: bridge
        labels:
            - "lumo.network=internal"

volumes:
    valkey-data:
        name: lumo-valkey-data
        labels:
            - "lumo.volume=valkey-data"
            - "lumo.service=valkey"

    seq-data:
        name: lumo-seq-data
        labels:
            - "lumo.volume=seq-data"
            - "lumo.service=seq"

    jaeger-data:
        name: lumo-jaeger-data
        labels:
            - "lumo.volume=jaeger-data"
            - "lumo.service=jaeger"

    auth-database-data:
        name: lumo-auth-database-data
        labels:
            - "lumo.volume=auth-database-data"
            - "lumo.service=auth-database"

    main-database-data:
        name: lumo-main-database-data
        labels:
            - "lumo.volume=main-database-data"
            - "lumo.service=main-database"

    rabbitmq-data:
        name: lumo-rabbitmq-data
        labels:
            - "lumo.volume=rabbitmq-data"
            - "lumo.service=rabbitmq"

    notifications-database-data:
        name: lumo-notifications-database-data
        labels:
            - "lumo.volume=notifications-database-data"
            - "lumo.service=notifications-database"
